### ISSUE TITLE
Addition/Removing of sectors to existing pool malfunctions latest sector selection.

### ISSUE THREAD

**Issue by Abdul-Samad-Saleem** [xoseperez/eeprom32_rotate#2]
I have come across a situation where the begin method of eeprom32_rotate is always selecting the last sector as the latest sector on every power reset of ESP32.  Below is the list of the eeprom sectors and the corresponding magic bytes.(first sector is eeprom0 with magic byte value 10).
Sector   name | Magic Value
-- | --
eeprom0 | 10
eeprom1 | 11
eeprom2 | 12
eeprom3 | 13
eeprom4 | 14
eeprom5 | 15
eeprom6 | 16
eeprom7 | 17
eeprom8 | 18
eeprom9 | 19
eeprom10 | 20
eeprom11 | 21
eeprom12 | 22
eeprom13 | 23
eeprom14 | 24
eeprom15 | 25
eeprom16 | 26
eeprom17 | 27
eeprom18 | 28
eeprom19 | 29
eeprom20 | 30
eeprom21 | 31
eeprom22 | 32
eeprom23 | 33
eeprom24 | 34
eeprom25 | 35
eeprom26 | 5
eeprom27 | 6
eeprom28 | 7
eeprom29 | 8
eeprom30 | 9
 The eeprom begin method used for initializing  always selects eeprom30 as the current sector. On subsequent commits the sector roll over to eeprom0 and then to eeprom1,eeprom2 so on. However on power reset it again goes back to eeprom30.
      I understand that this is happening due to the library logic for selecting the current sector. I think that in my case the misalignment of magic bytes occurred due to reducing/increasing the size of eeprom pool during different firmware updates of the device.
    As a fix I have once manually committed to eeprom 31 times to re-write all the magic bytes but  it would be better to have some fix for re-adjusting the unaligned magic bytes case this happens.

**Comment by xoseperez** [comment]
@Abdul-Samad-Saleem This should be fixed now with 0.9.2. Can you check this? 
See https://github.com/xoseperez/eeprom_rotate/issues/4

**Comment by Abdul-Samad-Saleem** [comment]
@xoseperez I will update you after testing

**Comment by Abdul-Samad-Saleem** [comment]
The revised logic for selecting the latest sector seems to have fixed the issue.
