### ISSUE TITLE
Compiler error: suggest parentheses around assignment used as truth value

### ISSUE THREAD

**Issue by thijsdebont** [xoseperez/eeprom32_rotate#4]
Using ESP32 board version 1.0.1 and Arduino IDE 1.8.8, the compiler exits with the error: suggest parentheses around assignment used as truth value  } while (iterator = esp_partition_next(iterator));. Adding an extra set of parentheses fixes the error.

**Comment by xoseperez** [comment]
This was fixed with #3, but not released yet.

**Comment by xoseperez** [comment]
Just released it as 0.9.3. Will soon be available in in Arduino IDE.
