### ISSUE TITLE
not working on latest ESP32 packages

### ISSUE THREAD

**Issue by AndreWillems** [xoseperez/eeprom32_rotate#7]
hi,

I've been using this library for some time now and it works fine on the ESP packages 1.0.1 and 1.0.2.
but when I recompile the same code with a later package, 1.0.3 or 1.0.4, it doesn't;

connecting partitions works, offset() works, commit() works, but all data is 0x00, before and after write()/commit().

anybody got the same issue ? any idea how to fix this ? for now, need to stick to the older package....

thanks.

**Comment by harenber** [comment]
Hi,

stumbled across the same issue with a  WiFi LoRA 32(V2) from Heltec. Only the old 0.0.2-rc1 Heltec support library (which contains equally old ESP packages) work, newer ones show the same effect as @AndreWillems describes. No idea what is the real cause of this, but EEPROM (also the original EEPROM.h) seems to be really broken on ESP32 for quite a while.

**Comment by AndreWillems** [comment]
hi @harenber,

I decided to solve it differently, by using the SPIFFS filesystem instead, which also supports (automatic) wear levelling. 
It's just as easy to write a struct to a file than using the EEPROM rotate. works for me now for months.
